allowBuilds:
  esbuild: set this to true or false
  lzma-native: set this to true or false
  node-pty: set this to true or false
onlyBuiltDependencies:
  - electron
  - esbuild
  - "@electron/rebuild"
  - node-pty
  - lzma-native
